apiVersion: v2
name: tekton-base
description: helm chart for deploying tekton-pipelines
type: application
version: v0.60.2
appVersion: v0.60.2
dependencies:
  - name: sthings-helm-toolkit
    version: 2.4.58
    repository: oci://eu.gcr.io/stuttgart-things
maintainers:
  - name: Patrick Hermann
    email: patrick.hermann@sva.de
