---
name: base_os
namespace: sthings
requirements: |
  roles:
    - src: https://github.com/stuttgart-things/download-install-binary.git
      scm: git
      version: 2024.09.06
    - src: https://github.com/stuttgart-things/create-os-user.git
      scm: git
      version: 2024.05.03
    - src: https://github.com/stuttgart-things/install-requirements.git
      scm: git
      version: 2024.05.11
    - src: https://github.com/stuttgart-things/manage-filesystem.git
      scm: git
      version: 2024.06.07
    - src: https://github.com/stuttgart-things/install-configure-vault.git
      scm: git
      version: 2022.01.01
    - src: https://github.com/stuttgart-things/create-send-webhook.git
      scm: git
      version: 2024.09.06
    - src: https://github.com/stuttgart-things/manage-proxmox-resources.git
      scm: git
      version: 2024.05.27